# Generated by Django 6.0 on 2026-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_page",
            "0002_article_category_tag_delete_post_article_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
