# Generated by Django 6.0 on 2025-12-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("author", "Author"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
