# Generated by Django 6.0 on 2026-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
